//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vera.Austria.DEP
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NetworkCredential", Namespace = "https://www.e-tresor.at/")]
    public partial class NetworkCredential : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string UserNameField;

        private string PasswordField;

        private Vera.Austria.DEP.SecureString SecurePasswordField;

        private string DomainField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public Vera.Austria.DEP.SecureString SecurePassword
        {
            get
            {
                return this.SecurePasswordField;
            }
            set
            {
                this.SecurePasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SecureString", Namespace = "https://www.e-tresor.at/")]
    public partial class SecureString : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Result", Namespace = "https://www.e-tresor.at/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vera.Austria.DEP.NetworkCredential))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vera.Austria.DEP.SecureString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vera.Austria.DEP.State))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Vera.Austria.DEP.RKSVMetaData))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private object DataField;

        private string DataTypeField;

        private string DescriptionField;

        private Vera.Austria.DEP.State ResultStateField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public object Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string DataType
        {
            get
            {
                return this.DataTypeField;
            }
            set
            {
                this.DataTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public Vera.Austria.DEP.State ResultState
        {
            get
            {
                return this.ResultStateField;
            }
            set
            {
                this.ResultStateField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "State", Namespace = "https://www.e-tresor.at/")]
    public enum State : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unprocessed = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationError = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FunctionError = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaintenanceActive = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileAlreadyExists = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequiredParameterNotSet = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterIdMismatch = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiptNumberAlreadyExists = 10,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDEPFileFormat = 11,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpgradeInactive = 12,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RKSVMetaData", Namespace = "https://www.e-tresor.at/")]
    public partial class RKSVMetaData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string RegisterIdField;

        private string Base64AESKeyField;

        private string AlgorithmusField;

        private string CertificateField;

        private string CertificateSerialNumberHEXField;

        private string CompanyIdentifierField;

        private string ZDAIDField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string RegisterId
        {
            get
            {
                return this.RegisterIdField;
            }
            set
            {
                this.RegisterIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Base64AESKey
        {
            get
            {
                return this.Base64AESKeyField;
            }
            set
            {
                this.Base64AESKeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Algorithmus
        {
            get
            {
                return this.AlgorithmusField;
            }
            set
            {
                this.AlgorithmusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string Certificate
        {
            get
            {
                return this.CertificateField;
            }
            set
            {
                this.CertificateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string CertificateSerialNumberHEX
        {
            get
            {
                return this.CertificateSerialNumberHEXField;
            }
            set
            {
                this.CertificateSerialNumberHEXField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string CompanyIdentifier
        {
            get
            {
                return this.CompanyIdentifierField;
            }
            set
            {
                this.CompanyIdentifierField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string ZDAID
        {
            get
            {
                return this.ZDAIDField;
            }
            set
            {
                this.ZDAIDField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://www.e-tresor.at/", ConfigurationName = "Vera.Austria.DEP.rksv_depSoap")]
    public interface rksv_depSoap
    {

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/Add", ReplyAction = "*")]
        Vera.Austria.DEP.AddResponse Add(Vera.Austria.DEP.AddRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/Add", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.AddResponse> AddAsync(Vera.Austria.DEP.AddRequest request);

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/UploadDEPFile", ReplyAction = "*")]
        Vera.Austria.DEP.UploadDEPFileResponse UploadDEPFile(Vera.Austria.DEP.UploadDEPFileRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/UploadDEPFile", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.UploadDEPFileResponse> UploadDEPFileAsync(Vera.Austria.DEP.UploadDEPFileRequest request);

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/DownloadDEPFile", ReplyAction = "*")]
        Vera.Austria.DEP.DownloadDEPFileResponse DownloadDEPFile(Vera.Austria.DEP.DownloadDEPFileRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/DownloadDEPFile", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.DownloadDEPFileResponse> DownloadDEPFileAsync(Vera.Austria.DEP.DownloadDEPFileRequest request);

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/DeleteDEPFile", ReplyAction = "*")]
        Vera.Austria.DEP.DeleteDEPFileResponse DeleteDEPFile(Vera.Austria.DEP.DeleteDEPFileRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/DeleteDEPFile", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.DeleteDEPFileResponse> DeleteDEPFileAsync(Vera.Austria.DEP.DeleteDEPFileRequest request);

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/Export", ReplyAction = "*")]
        Vera.Austria.DEP.ExportResponse Export(Vera.Austria.DEP.ExportRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/Export", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.ExportResponse> ExportAsync(Vera.Austria.DEP.ExportRequest request);

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/Register", ReplyAction = "*")]
        Vera.Austria.DEP.RegisterResponse Register(Vera.Austria.DEP.RegisterRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/Register", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.RegisterResponse> RegisterAsync(Vera.Austria.DEP.RegisterRequest request);

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/SaveRKSVMetaData", ReplyAction = "*")]
        Vera.Austria.DEP.SaveRKSVMetaDataResponse SaveRKSVMetaData(Vera.Austria.DEP.SaveRKSVMetaDataRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/SaveRKSVMetaData", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.SaveRKSVMetaDataResponse> SaveRKSVMetaDataAsync(Vera.Austria.DEP.SaveRKSVMetaDataRequest request);

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/ReadRKSVMetaData", ReplyAction = "*")]
        Vera.Austria.DEP.ReadRKSVMetaDataResponse ReadRKSVMetaData(Vera.Austria.DEP.ReadRKSVMetaDataRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/ReadRKSVMetaData", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.ReadRKSVMetaDataResponse> ReadRKSVMetaDataAsync(Vera.Austria.DEP.ReadRKSVMetaDataRequest request);

        // CODEGEN: Generating message contract since element name credential from namespace https://www.e-tresor.at/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/DeleteAllDEPEntriesForRegisterId", ReplyAction = "*")]
        Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdResponse DeleteAllDEPEntriesForRegisterId(Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.e-tresor.at/DeleteAllDEPEntriesForRegisterId", ReplyAction = "*")]
        System.Threading.Tasks.Task<Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdResponse> DeleteAllDEPEntriesForRegisterIdAsync(Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class AddRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Add", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.AddRequestBody Body;

        public AddRequest()
        {
        }

        public AddRequest(Vera.Austria.DEP.AddRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class AddRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string entry;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string signedEntry;

        public AddRequestBody()
        {
        }

        public AddRequestBody(Vera.Austria.DEP.NetworkCredential credential, string entry, string signedEntry)
        {
            this.credential = credential;
            this.entry = entry;
            this.signedEntry = signedEntry;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class AddResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "AddResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.AddResponseBody Body;

        public AddResponse()
        {
        }

        public AddResponse(Vera.Austria.DEP.AddResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class AddResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result AddResult;

        public AddResponseBody()
        {
        }

        public AddResponseBody(Vera.Austria.DEP.Result AddResult)
        {
            this.AddResult = AddResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UploadDEPFileRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UploadDEPFile", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.UploadDEPFileRequestBody Body;

        public UploadDEPFileRequest()
        {
        }

        public UploadDEPFileRequest(Vera.Austria.DEP.UploadDEPFileRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class UploadDEPFileRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string fileName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public byte[] fileData;

        public UploadDEPFileRequestBody()
        {
        }

        public UploadDEPFileRequestBody(Vera.Austria.DEP.NetworkCredential credential, string fileName, byte[] fileData)
        {
            this.credential = credential;
            this.fileName = fileName;
            this.fileData = fileData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class UploadDEPFileResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UploadDEPFileResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.UploadDEPFileResponseBody Body;

        public UploadDEPFileResponse()
        {
        }

        public UploadDEPFileResponse(Vera.Austria.DEP.UploadDEPFileResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class UploadDEPFileResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result UploadDEPFileResult;

        public UploadDEPFileResponseBody()
        {
        }

        public UploadDEPFileResponseBody(Vera.Austria.DEP.Result UploadDEPFileResult)
        {
            this.UploadDEPFileResult = UploadDEPFileResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class DownloadDEPFileRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "DownloadDEPFile", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.DownloadDEPFileRequestBody Body;

        public DownloadDEPFileRequest()
        {
        }

        public DownloadDEPFileRequest(Vera.Austria.DEP.DownloadDEPFileRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class DownloadDEPFileRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string fileName;

        public DownloadDEPFileRequestBody()
        {
        }

        public DownloadDEPFileRequestBody(Vera.Austria.DEP.NetworkCredential credential, string fileName)
        {
            this.credential = credential;
            this.fileName = fileName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class DownloadDEPFileResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "DownloadDEPFileResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.DownloadDEPFileResponseBody Body;

        public DownloadDEPFileResponse()
        {
        }

        public DownloadDEPFileResponse(Vera.Austria.DEP.DownloadDEPFileResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class DownloadDEPFileResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result DownloadDEPFileResult;

        public DownloadDEPFileResponseBody()
        {
        }

        public DownloadDEPFileResponseBody(Vera.Austria.DEP.Result DownloadDEPFileResult)
        {
            this.DownloadDEPFileResult = DownloadDEPFileResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class DeleteDEPFileRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "DeleteDEPFile", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.DeleteDEPFileRequestBody Body;

        public DeleteDEPFileRequest()
        {
        }

        public DeleteDEPFileRequest(Vera.Austria.DEP.DeleteDEPFileRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class DeleteDEPFileRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string fileName;

        public DeleteDEPFileRequestBody()
        {
        }

        public DeleteDEPFileRequestBody(Vera.Austria.DEP.NetworkCredential credential, string fileName)
        {
            this.credential = credential;
            this.fileName = fileName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class DeleteDEPFileResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "DeleteDEPFileResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.DeleteDEPFileResponseBody Body;

        public DeleteDEPFileResponse()
        {
        }

        public DeleteDEPFileResponse(Vera.Austria.DEP.DeleteDEPFileResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class DeleteDEPFileResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result DeleteDEPFileResult;

        public DeleteDEPFileResponseBody()
        {
        }

        public DeleteDEPFileResponseBody(Vera.Austria.DEP.Result DeleteDEPFileResult)
        {
            this.DeleteDEPFileResult = DeleteDEPFileResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ExportRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Export", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.ExportRequestBody Body;

        public ExportRequest()
        {
        }

        public ExportRequest(Vera.Austria.DEP.ExportRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class ExportRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.DateTime startDate;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.DateTime endDate;

        public ExportRequestBody()
        {
        }

        public ExportRequestBody(Vera.Austria.DEP.NetworkCredential credential, System.DateTime startDate, System.DateTime endDate)
        {
            this.credential = credential;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ExportResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ExportResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.ExportResponseBody Body;

        public ExportResponse()
        {
        }

        public ExportResponse(Vera.Austria.DEP.ExportResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class ExportResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result ExportResult;

        public ExportResponseBody()
        {
        }

        public ExportResponseBody(Vera.Austria.DEP.Result ExportResult)
        {
            this.ExportResult = ExportResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "Register", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.RegisterRequestBody Body;

        public RegisterRequest()
        {
        }

        public RegisterRequest(Vera.Austria.DEP.RegisterRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class RegisterRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string partnerNr;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string partnerEmail;

        public RegisterRequestBody()
        {
        }

        public RegisterRequestBody(Vera.Austria.DEP.NetworkCredential credential, string partnerNr, string partnerEmail)
        {
            this.credential = credential;
            this.partnerNr = partnerNr;
            this.partnerEmail = partnerEmail;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.RegisterResponseBody Body;

        public RegisterResponse()
        {
        }

        public RegisterResponse(Vera.Austria.DEP.RegisterResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class RegisterResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result RegisterResult;

        public RegisterResponseBody()
        {
        }

        public RegisterResponseBody(Vera.Austria.DEP.Result RegisterResult)
        {
            this.RegisterResult = RegisterResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SaveRKSVMetaDataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SaveRKSVMetaData", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.SaveRKSVMetaDataRequestBody Body;

        public SaveRKSVMetaDataRequest()
        {
        }

        public SaveRKSVMetaDataRequest(Vera.Austria.DEP.SaveRKSVMetaDataRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class SaveRKSVMetaDataRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public Vera.Austria.DEP.RKSVMetaData metaData;

        public SaveRKSVMetaDataRequestBody()
        {
        }

        public SaveRKSVMetaDataRequestBody(Vera.Austria.DEP.NetworkCredential credential, Vera.Austria.DEP.RKSVMetaData metaData)
        {
            this.credential = credential;
            this.metaData = metaData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SaveRKSVMetaDataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SaveRKSVMetaDataResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.SaveRKSVMetaDataResponseBody Body;

        public SaveRKSVMetaDataResponse()
        {
        }

        public SaveRKSVMetaDataResponse(Vera.Austria.DEP.SaveRKSVMetaDataResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class SaveRKSVMetaDataResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result SaveRKSVMetaDataResult;

        public SaveRKSVMetaDataResponseBody()
        {
        }

        public SaveRKSVMetaDataResponseBody(Vera.Austria.DEP.Result SaveRKSVMetaDataResult)
        {
            this.SaveRKSVMetaDataResult = SaveRKSVMetaDataResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ReadRKSVMetaDataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ReadRKSVMetaData", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.ReadRKSVMetaDataRequestBody Body;

        public ReadRKSVMetaDataRequest()
        {
        }

        public ReadRKSVMetaDataRequest(Vera.Austria.DEP.ReadRKSVMetaDataRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class ReadRKSVMetaDataRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string registerId;

        public ReadRKSVMetaDataRequestBody()
        {
        }

        public ReadRKSVMetaDataRequestBody(Vera.Austria.DEP.NetworkCredential credential, string registerId)
        {
            this.credential = credential;
            this.registerId = registerId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ReadRKSVMetaDataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ReadRKSVMetaDataResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.ReadRKSVMetaDataResponseBody Body;

        public ReadRKSVMetaDataResponse()
        {
        }

        public ReadRKSVMetaDataResponse(Vera.Austria.DEP.ReadRKSVMetaDataResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class ReadRKSVMetaDataResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result ReadRKSVMetaDataResult;

        public ReadRKSVMetaDataResponseBody()
        {
        }

        public ReadRKSVMetaDataResponseBody(Vera.Austria.DEP.Result ReadRKSVMetaDataResult)
        {
            this.ReadRKSVMetaDataResult = ReadRKSVMetaDataResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class DeleteAllDEPEntriesForRegisterIdRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "DeleteAllDEPEntriesForRegisterId", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequestBody Body;

        public DeleteAllDEPEntriesForRegisterIdRequest()
        {
        }

        public DeleteAllDEPEntriesForRegisterIdRequest(Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class DeleteAllDEPEntriesForRegisterIdRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.NetworkCredential credential;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string registerId;

        public DeleteAllDEPEntriesForRegisterIdRequestBody()
        {
        }

        public DeleteAllDEPEntriesForRegisterIdRequestBody(Vera.Austria.DEP.NetworkCredential credential, string registerId)
        {
            this.credential = credential;
            this.registerId = registerId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class DeleteAllDEPEntriesForRegisterIdResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "DeleteAllDEPEntriesForRegisterIdResponse", Namespace = "https://www.e-tresor.at/", Order = 0)]
        public Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdResponseBody Body;

        public DeleteAllDEPEntriesForRegisterIdResponse()
        {
        }

        public DeleteAllDEPEntriesForRegisterIdResponse(Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://www.e-tresor.at/")]
    public partial class DeleteAllDEPEntriesForRegisterIdResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Vera.Austria.DEP.Result DeleteAllDEPEntriesForRegisterIdResult;

        public DeleteAllDEPEntriesForRegisterIdResponseBody()
        {
        }

        public DeleteAllDEPEntriesForRegisterIdResponseBody(Vera.Austria.DEP.Result DeleteAllDEPEntriesForRegisterIdResult)
        {
            this.DeleteAllDEPEntriesForRegisterIdResult = DeleteAllDEPEntriesForRegisterIdResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface rksv_depSoapChannel : Vera.Austria.DEP.rksv_depSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class rksv_depSoapClient : System.ServiceModel.ClientBase<Vera.Austria.DEP.rksv_depSoap>, Vera.Austria.DEP.rksv_depSoap
    {

        public rksv_depSoapClient()
        {
        }

        public rksv_depSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public rksv_depSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public rksv_depSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public rksv_depSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.AddResponse Vera.Austria.DEP.rksv_depSoap.Add(Vera.Austria.DEP.AddRequest request)
        {
            return base.Channel.Add(request);
        }

        public Vera.Austria.DEP.Result Add(Vera.Austria.DEP.NetworkCredential credential, string entry, string signedEntry)
        {
            Vera.Austria.DEP.AddRequest inValue = new Vera.Austria.DEP.AddRequest();
            inValue.Body = new Vera.Austria.DEP.AddRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.entry = entry;
            inValue.Body.signedEntry = signedEntry;
            Vera.Austria.DEP.AddResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.AddResponse> Vera.Austria.DEP.rksv_depSoap.AddAsync(Vera.Austria.DEP.AddRequest request)
        {
            return base.Channel.AddAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.AddResponse> AddAsync(Vera.Austria.DEP.NetworkCredential credential, string entry, string signedEntry)
        {
            Vera.Austria.DEP.AddRequest inValue = new Vera.Austria.DEP.AddRequest();
            inValue.Body = new Vera.Austria.DEP.AddRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.entry = entry;
            inValue.Body.signedEntry = signedEntry;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).AddAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.UploadDEPFileResponse Vera.Austria.DEP.rksv_depSoap.UploadDEPFile(Vera.Austria.DEP.UploadDEPFileRequest request)
        {
            return base.Channel.UploadDEPFile(request);
        }

        public Vera.Austria.DEP.Result UploadDEPFile(Vera.Austria.DEP.NetworkCredential credential, string fileName, byte[] fileData)
        {
            Vera.Austria.DEP.UploadDEPFileRequest inValue = new Vera.Austria.DEP.UploadDEPFileRequest();
            inValue.Body = new Vera.Austria.DEP.UploadDEPFileRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.fileName = fileName;
            inValue.Body.fileData = fileData;
            Vera.Austria.DEP.UploadDEPFileResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).UploadDEPFile(inValue);
            return retVal.Body.UploadDEPFileResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.UploadDEPFileResponse> Vera.Austria.DEP.rksv_depSoap.UploadDEPFileAsync(Vera.Austria.DEP.UploadDEPFileRequest request)
        {
            return base.Channel.UploadDEPFileAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.UploadDEPFileResponse> UploadDEPFileAsync(Vera.Austria.DEP.NetworkCredential credential, string fileName, byte[] fileData)
        {
            Vera.Austria.DEP.UploadDEPFileRequest inValue = new Vera.Austria.DEP.UploadDEPFileRequest();
            inValue.Body = new Vera.Austria.DEP.UploadDEPFileRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.fileName = fileName;
            inValue.Body.fileData = fileData;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).UploadDEPFileAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.DownloadDEPFileResponse Vera.Austria.DEP.rksv_depSoap.DownloadDEPFile(Vera.Austria.DEP.DownloadDEPFileRequest request)
        {
            return base.Channel.DownloadDEPFile(request);
        }

        public Vera.Austria.DEP.Result DownloadDEPFile(Vera.Austria.DEP.NetworkCredential credential, string fileName)
        {
            Vera.Austria.DEP.DownloadDEPFileRequest inValue = new Vera.Austria.DEP.DownloadDEPFileRequest();
            inValue.Body = new Vera.Austria.DEP.DownloadDEPFileRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.fileName = fileName;
            Vera.Austria.DEP.DownloadDEPFileResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).DownloadDEPFile(inValue);
            return retVal.Body.DownloadDEPFileResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.DownloadDEPFileResponse> Vera.Austria.DEP.rksv_depSoap.DownloadDEPFileAsync(Vera.Austria.DEP.DownloadDEPFileRequest request)
        {
            return base.Channel.DownloadDEPFileAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.DownloadDEPFileResponse> DownloadDEPFileAsync(Vera.Austria.DEP.NetworkCredential credential, string fileName)
        {
            Vera.Austria.DEP.DownloadDEPFileRequest inValue = new Vera.Austria.DEP.DownloadDEPFileRequest();
            inValue.Body = new Vera.Austria.DEP.DownloadDEPFileRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.fileName = fileName;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).DownloadDEPFileAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.DeleteDEPFileResponse Vera.Austria.DEP.rksv_depSoap.DeleteDEPFile(Vera.Austria.DEP.DeleteDEPFileRequest request)
        {
            return base.Channel.DeleteDEPFile(request);
        }

        public Vera.Austria.DEP.Result DeleteDEPFile(Vera.Austria.DEP.NetworkCredential credential, string fileName)
        {
            Vera.Austria.DEP.DeleteDEPFileRequest inValue = new Vera.Austria.DEP.DeleteDEPFileRequest();
            inValue.Body = new Vera.Austria.DEP.DeleteDEPFileRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.fileName = fileName;
            Vera.Austria.DEP.DeleteDEPFileResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).DeleteDEPFile(inValue);
            return retVal.Body.DeleteDEPFileResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.DeleteDEPFileResponse> Vera.Austria.DEP.rksv_depSoap.DeleteDEPFileAsync(Vera.Austria.DEP.DeleteDEPFileRequest request)
        {
            return base.Channel.DeleteDEPFileAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.DeleteDEPFileResponse> DeleteDEPFileAsync(Vera.Austria.DEP.NetworkCredential credential, string fileName)
        {
            Vera.Austria.DEP.DeleteDEPFileRequest inValue = new Vera.Austria.DEP.DeleteDEPFileRequest();
            inValue.Body = new Vera.Austria.DEP.DeleteDEPFileRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.fileName = fileName;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).DeleteDEPFileAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.ExportResponse Vera.Austria.DEP.rksv_depSoap.Export(Vera.Austria.DEP.ExportRequest request)
        {
            return base.Channel.Export(request);
        }

        public Vera.Austria.DEP.Result Export(Vera.Austria.DEP.NetworkCredential credential, System.DateTime startDate, System.DateTime endDate)
        {
            Vera.Austria.DEP.ExportRequest inValue = new Vera.Austria.DEP.ExportRequest();
            inValue.Body = new Vera.Austria.DEP.ExportRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            Vera.Austria.DEP.ExportResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).Export(inValue);
            return retVal.Body.ExportResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.ExportResponse> Vera.Austria.DEP.rksv_depSoap.ExportAsync(Vera.Austria.DEP.ExportRequest request)
        {
            return base.Channel.ExportAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.ExportResponse> ExportAsync(Vera.Austria.DEP.NetworkCredential credential, System.DateTime startDate, System.DateTime endDate)
        {
            Vera.Austria.DEP.ExportRequest inValue = new Vera.Austria.DEP.ExportRequest();
            inValue.Body = new Vera.Austria.DEP.ExportRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).ExportAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.RegisterResponse Vera.Austria.DEP.rksv_depSoap.Register(Vera.Austria.DEP.RegisterRequest request)
        {
            return base.Channel.Register(request);
        }

        public Vera.Austria.DEP.Result Register(Vera.Austria.DEP.NetworkCredential credential, string partnerNr, string partnerEmail)
        {
            Vera.Austria.DEP.RegisterRequest inValue = new Vera.Austria.DEP.RegisterRequest();
            inValue.Body = new Vera.Austria.DEP.RegisterRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.partnerNr = partnerNr;
            inValue.Body.partnerEmail = partnerEmail;
            Vera.Austria.DEP.RegisterResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.RegisterResponse> Vera.Austria.DEP.rksv_depSoap.RegisterAsync(Vera.Austria.DEP.RegisterRequest request)
        {
            return base.Channel.RegisterAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.RegisterResponse> RegisterAsync(Vera.Austria.DEP.NetworkCredential credential, string partnerNr, string partnerEmail)
        {
            Vera.Austria.DEP.RegisterRequest inValue = new Vera.Austria.DEP.RegisterRequest();
            inValue.Body = new Vera.Austria.DEP.RegisterRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.partnerNr = partnerNr;
            inValue.Body.partnerEmail = partnerEmail;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).RegisterAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.SaveRKSVMetaDataResponse Vera.Austria.DEP.rksv_depSoap.SaveRKSVMetaData(Vera.Austria.DEP.SaveRKSVMetaDataRequest request)
        {
            return base.Channel.SaveRKSVMetaData(request);
        }

        public Vera.Austria.DEP.Result SaveRKSVMetaData(Vera.Austria.DEP.NetworkCredential credential, Vera.Austria.DEP.RKSVMetaData metaData)
        {
            Vera.Austria.DEP.SaveRKSVMetaDataRequest inValue = new Vera.Austria.DEP.SaveRKSVMetaDataRequest();
            inValue.Body = new Vera.Austria.DEP.SaveRKSVMetaDataRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.metaData = metaData;
            Vera.Austria.DEP.SaveRKSVMetaDataResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).SaveRKSVMetaData(inValue);
            return retVal.Body.SaveRKSVMetaDataResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.SaveRKSVMetaDataResponse> Vera.Austria.DEP.rksv_depSoap.SaveRKSVMetaDataAsync(Vera.Austria.DEP.SaveRKSVMetaDataRequest request)
        {
            return base.Channel.SaveRKSVMetaDataAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.SaveRKSVMetaDataResponse> SaveRKSVMetaDataAsync(Vera.Austria.DEP.NetworkCredential credential, Vera.Austria.DEP.RKSVMetaData metaData)
        {
            Vera.Austria.DEP.SaveRKSVMetaDataRequest inValue = new Vera.Austria.DEP.SaveRKSVMetaDataRequest();
            inValue.Body = new Vera.Austria.DEP.SaveRKSVMetaDataRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.metaData = metaData;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).SaveRKSVMetaDataAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.ReadRKSVMetaDataResponse Vera.Austria.DEP.rksv_depSoap.ReadRKSVMetaData(Vera.Austria.DEP.ReadRKSVMetaDataRequest request)
        {
            return base.Channel.ReadRKSVMetaData(request);
        }

        public Vera.Austria.DEP.Result ReadRKSVMetaData(Vera.Austria.DEP.NetworkCredential credential, string registerId)
        {
            Vera.Austria.DEP.ReadRKSVMetaDataRequest inValue = new Vera.Austria.DEP.ReadRKSVMetaDataRequest();
            inValue.Body = new Vera.Austria.DEP.ReadRKSVMetaDataRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.registerId = registerId;
            Vera.Austria.DEP.ReadRKSVMetaDataResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).ReadRKSVMetaData(inValue);
            return retVal.Body.ReadRKSVMetaDataResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.ReadRKSVMetaDataResponse> Vera.Austria.DEP.rksv_depSoap.ReadRKSVMetaDataAsync(Vera.Austria.DEP.ReadRKSVMetaDataRequest request)
        {
            return base.Channel.ReadRKSVMetaDataAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.ReadRKSVMetaDataResponse> ReadRKSVMetaDataAsync(Vera.Austria.DEP.NetworkCredential credential, string registerId)
        {
            Vera.Austria.DEP.ReadRKSVMetaDataRequest inValue = new Vera.Austria.DEP.ReadRKSVMetaDataRequest();
            inValue.Body = new Vera.Austria.DEP.ReadRKSVMetaDataRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.registerId = registerId;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).ReadRKSVMetaDataAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdResponse Vera.Austria.DEP.rksv_depSoap.DeleteAllDEPEntriesForRegisterId(Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequest request)
        {
            return base.Channel.DeleteAllDEPEntriesForRegisterId(request);
        }

        public Vera.Austria.DEP.Result DeleteAllDEPEntriesForRegisterId(Vera.Austria.DEP.NetworkCredential credential, string registerId)
        {
            Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequest inValue = new Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequest();
            inValue.Body = new Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.registerId = registerId;
            Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdResponse retVal = ((Vera.Austria.DEP.rksv_depSoap)(this)).DeleteAllDEPEntriesForRegisterId(inValue);
            return retVal.Body.DeleteAllDEPEntriesForRegisterIdResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdResponse> Vera.Austria.DEP.rksv_depSoap.DeleteAllDEPEntriesForRegisterIdAsync(Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequest request)
        {
            return base.Channel.DeleteAllDEPEntriesForRegisterIdAsync(request);
        }

        public System.Threading.Tasks.Task<Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdResponse> DeleteAllDEPEntriesForRegisterIdAsync(Vera.Austria.DEP.NetworkCredential credential, string registerId)
        {
            Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequest inValue = new Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequest();
            inValue.Body = new Vera.Austria.DEP.DeleteAllDEPEntriesForRegisterIdRequestBody();
            inValue.Body.credential = credential;
            inValue.Body.registerId = registerId;
            return ((Vera.Austria.DEP.rksv_depSoap)(this)).DeleteAllDEPEntriesForRegisterIdAsync(inValue);
        }
    }
}
