using System.Collections.Generic;

namespace Vera.StandardAuditFileTaxation
{
  public abstract class SourceDocument
  {
    /// <summary>
    /// Non-negative number of the accounting period.
    /// </summary>
    public int Period { get; set; }

    /// <summary>
    /// Year of the accounting period.
    /// </summary>
    public int PeriodYear { get; set; }

    /// <summary>
    /// Cross-reference to the GL posting.
    /// </summary>
    public string TransactionID { get; set; }

    /// <summary>
    /// Unique number generated by the system for the invoice.
    /// </summary>
    public string SystemID { get; set; }

    /// <summary>
    /// System generated ID for the batch.
    /// </summary>
    public string BatchID { get; set; }

    public Totals Totals { get; set; }

    public ICollection<Settlement> Settlements { get; set; }
  }
}