using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using Vera.Poland.Models.Responses;

namespace Vera.Poland.Protocol
{
  [SuppressMessage("ReSharper", "StringLiteralTypo")]
  internal class FiscalPrinterErrors
  {
    public static ErrorWithCode GetErrorFor(byte[] errorCode)
    {
      var intErrorCode = ConvertToInt(errorCode);
    
      return GetErrorFor(intErrorCode);
    }
    
    public static ErrorWithCode GetErrorFor(int errorCode)
    {
      return !ErrorMap.ContainsKey(errorCode)
        ? null
        : new ErrorWithCode
        {
          Code = errorCode,
          Description = ErrorMap[errorCode]
        };
    }
    
    /// <summary>
    /// For now we only accept array of two bytes
    /// </summary>
    private static int ConvertToInt(IReadOnlyList<byte> array)
    {
      if (array.Count != 2)
      {
        throw new InvalidDataException("Only accepting 2 bytes");
      }

      return (array[0] << 8) | array[1];
    }

    private static readonly Dictionary<int, string> ErrorMap = new Dictionary<int, string>
    {
      { 0x2000, "No access, required service or producer jumper" },
      { 0x2001, "A service jumper is required" },
      { 0x2002, "Passwords are different" },
      { 0x2010, "Sec: no access, enter unlocking key" },
      { 0x3000, "Unknown parameter" },
      { 0x3001, "Invalid parameter value" },
      { 0x3002, "Another master protocol is already running" },
      { 0x3100, "The printer is initiated, operation not allowed" },
      { 0x3101, "The printer is serialized, operation not allowed" },
      { 0x3102, "The printer is fiscalized, operation not allowed" },
      { 0x3110, "The printer is not initiated, operation not allowed" },
      { 0x3111, "The printer is not serialized, operation not allowed" },
      { 0x3112, "The printer is not fiscalized, operation not allowed" },
      { 0x3113, "Unlocking RAM is not needed" },
      { 0x3114, "Unlocking fiscal memory is not needed" },
      { 0x3115, "Wrong unique number format" },
      { 0x3116, "Wrong NIP number format" },
      { 0x3119, "Fiscalisation canceled" },
      { 0x3120, "Incorrect tax office code format" },
      { 0x3121, "Wrong ID number format" },
      { 0x3122, "Invalid cash register ownership type" },
      { 0x3123, "Invalid printer user type" },
      { 0x3124, "Data for fiscalisation incompatible with fiscal memory" },
      { 0x3125, "Firmware version incompatible with fiscal memory" },
      { 0x3126, "Data in protected memory incompatible with fiscal memory" },
      { 0x3127, "The printer public key incompatible with fiscal memory" },
      { 0x3200, "Invalid key to unlock fiscal memory" },
      { 0x3201, "The fiscal memory signature was not generated or is invalid" },
      { 0x3202, "Fiscal memory is already signed" },
      { 0x3203, "The fiscal memory is already formatted" },
      { 0x3204, "The fiscal memory is not empty" },
      { 0x3300, "The new time and date are earlier than the last record in the fiscal memory" },
      { 0x3301, "Setting the date and time out of the allowed range: see fiscal law" },
      { 0x3302, "Defined header is empty" },
      { 0x3305, "Taxpayer name too long" },
      { 0x3306, "Too many currency names" },
      { 0x3800, "Empty string" },
      { 0x3801, "Out of range" },
      { 0x3802, "Invalid character" },
      { 0x3803, "Not enough space for string" },
      { 0x3804, "Too much space for the string" },
      { 0x4000, "Buffer overflow" },
      { 0x5000, "Wrong checksum of number" },
      { 0x5001, "Exceeding range when adding" },
      { 0x5002, "Exceeding range when subtracting" },
      { 0x5003, "Exceeding range by multiplication" },
      { 0x5004, "Exceeding range when splitting" },
      { 0x5005, "Divide by zero" },
      { 0x5006, "Attempt to save the totalizer non-transactionally" },
      { 0x5007, "Too many operations, the array on copies is full" },
      { 0x5008, "Unauthorized negative value" },
      { 0x5009, "The limit for daily values has been exceeded" },
      { 0x500A, "The limit for receipt value exceeded" },
      { 0x500B, "The limit for sales position value has been exceeded" },
      { 0x500C, "Rounding error" },
      { 0x500D, "Not initiated totalizer" },
      { 0x500E, "Wrong number of totalizer" },
      { 0x500F, "That totalizer does not exist" },
      { 0x5010, "Too many digits after the decimal point" },
      { 0x5011, "Value beyond the limits set by the user" },
      { 0x5100, "Wrong checksum of number (counters)" },
      { 0x5106, "Attempt to save the totalizer non-transactionally (counters)" },
      { 0x5107, "Too many operations, the array on copies is full (counters)" },
      { 0x5108, "Unauthorized negative value (counters)" },
      { 0x5109, "The limit for daily values has been exceeded (counters)" },
      { 0x510A, "The limit for receipt value exceeded (counters)" },
      { 0x510D, "Not initialized counter" },
      { 0x6000, "Unknown VAT rate code" },
      { 0x6001, "Undefined VAT rate" },
      { 0x6002, "Payment is undefined" },
      { 0x6003, "Payment is predefined" },
      { 0x6004, "Group is not defined" },
      { 0x6005, "Group is predefined" },
      { 0x6006, "Wrong header line number" },
      { 0x6007, "Wrong footer line number" },
      { 0x6008, "VAT calculation error" },
      { 0x600A, "VAT rates can not be set" },
      { 0x600D, "Not defined POS" },
      { 0x600E, "Not defined header" },
      { 0x600F, "tra.tot[_v]+tra.tot_diff[_v] can not be negative" },
      { 0x6010, "Price * quantity <> amount" },
      { 0x6011, "Zero sales" },
      { 0x6012, "Zero sum of the receipt" },
      { 0x6013, "Negative sum of receipt" },
      { 0x6014, "Incorrect receipt summary" },
      { 0x6015, "Access to fiscal memory is not allowed" },
      { 0x6016, "Available only in training or fiscal mode" },
      { 0x6017, "Operator not defined" },
      { 0x6018, "VAT rates not defined" },
      { 0x6019, "Defined table of VAT rates is not correct" },
      { 0x601A, "Sale is not possible, item is locked" },
      { 0x601B, "Allowed only in fiscal mode" },
      { 0x601C, "The fiscal memory is only to read" },
      { 0x601D, "Free display error" },
      { 0x601E, "Fiscal memory is not formatted" },
      { 0x601F, "Fiscal memory is not unlocked" },
      { 0x6020, "Allowed only in technological mode" },
      { 0x6021, "Negative rest" },
      { 0x6022, "The rest can not be positive when it was not paid" },
      { 0x6023, "Incorrect proportions at uplift or discount to the sum" },
      { 0x6024, "The rest amount is greater than the cash paid in" },
      { 0x6025, "The payout amount is too large" },
      { 0x6026, "There is no space in the receipt buffer for sales items" },
      { 0x6027, "The receipt item buffer is full" },
      { 0x602B, "Invalid VAT rate" },
      { 0x6030, "No SHA signature record" },
      { 0x6031, "SHA signatures are different" },
      { 0x6047, "The date / time of the currently running Z-report can not be earlier than the last saved record to FM" },
      { 0x6050, "Point of sale address is not defined" },
      { 0x6090, "The invoice control number is not valid" },
      { 0x60F0, "Totalizers are damaged" },
      { 0x60F1, "No data in selected range" },
      { 0x60F2, "Damaged start record range" },
      { 0x60F3, "Corrupted end-of-range record" },
      { 0x60F5, "Invalid data in protected memory" },
      { 0x60F6, "Cash register public key is not sent after exchange" },
      { 0x60F7, "CPD public key not downloaded" },
      { 0x6100, "Wrong commands sequence" },
      { 0x6101, "Receipt is open" },
      { 0x6102, "Invoice is open" },
      { 0x6103, "No sales item" },
      { 0x6104, "Not allowed in the sales phase" },
      { 0x6105, "Receipt is already summarized" },
      { 0x6106, "Receipt is not summarized" },
      { 0x6107, "Receipt in the payment phase" },
      { 0x6108, "A cancellation or correct summary is required" },
      { 0x6109, "Comment is not allowed at this time" },
      { 0x610A, "Receipt is not open" },
      { 0x610B, "Too many sales lines" },
      { 0x6110, "Application report open" },
      { 0x6111, "Application report closed" },
      { 0x6120, "Formatted report from the application open" },
      { 0x6121, "Formatted report from application - wrong line sequence" },
      { 0x6122, "Formatted report from the application is not open" },
      { 0x6130, "Commodity base test opened" },
      { 0x6131, "Commodity base test not open" },
      { 0x6160, "The daily report is open" },
      { 0x6161, "The period report is open" },
      { 0x6162, "Open VAT rate report" },
      { 0x6163, "Open service report" },
      { 0x6164, "Printing all signs in progress" },
      { 0x6165, "Printing new time and date in progress" },
      { 0x6166, "Printing new reader in progress" },
      { 0x6167, "Printing new VAT rates in progress" },
      { 0x6168, "Printing invoice verification in progress" },
      { 0x6169, "Printing X Report in progress" },
      { 0x616A, "Printing totalizers report in progres" },
      { 0x616B, "Printing report after runing power in progress" },
      { 0x616D, "It is not possible to print a duplicate of a daily report" },
      { 0x616E, "Close the sales period is required" },
      { 0x616F, "Printing commodity base report in progress" },
      { 0x6171, "The command is not allowed in this printout" },
      { 0x6175, "Printing barcode is impossible now, fiscal restriction" },
      { 0x6176, "Receipt during handling returnable packaging" },
      { 0x6177, "Receipt open" },
      { 0x6179, "Setting VAT rates is not allowed - totalizers restored from flash memory" },
      { 0x617E, "Raport zdarzeń otwarty" },
      { 0x6180, "Sales period opened, operation not allowed" },
      { 0x6181, "Fiscal day closed, operation not allowed" },
      { 0x6182, "EJ block closed" },
      { 0x6183, "First, dump the electronic journal data or send information about unsuccessful data archiving" },
      { 0x6189, "Close the day is required" },
      { 0x6200, "Wrong mode of receipt or invoice printing" },
      { 0x6201, "Invalid parameter" },
      { 0x6202, "Too long string" },
      { 0x6203, "Too short string" },
      { 0x6204, "Sign not allowed" },
      { 0x6205, "Word not allowed" },
      { 0x6206, "Empty string" },
      { 0x6207, "Invalid service report type" },
      { 0x6208, "Not allowed: date / time" },
      { 0x6209, "Incorrect product name on WZ receipt" },
      { 0x620A, "Incorrect product name" },
      { 0x620B, "This printout is blocked" },
      { 0x620C, "Wrong type of negative position" },
      { 0x620D, "Wrong type of discount or uplift" },
      { 0x620E, "Wrong Payment ID" },
      { 0x620F, "Too many free texts" },
      { 0x6210, "Wrong number of barcode signs" },
      { 0x6211, "Wrong sign in barcode" },
      { 0x6212, "Wrong barcode format" },
      { 0x6213, "Selected barcode is not supported" },
      { 0x6214, "Barcode error, change the parameters and send the command again" },
      { 0x6219, "Currency change with delay is only available in fiscal mode" },
      { 0x62E0, "Unknown command - sales application error" },
      { 0x62F0, "Printer busy with another command" },
      { 0x6400, "No access to Fiscal Memory" },
      { 0x6401, "Error writing to Fiscal Memory" },
      { 0x6402, "Error reading from Fiscal Memory" },
      { 0x6403, "Line checksum error" },
      { 0x6404, "Data checksum error" },
      { 0x6405, "Missing data" },
      { 0x6407, "Incorrect handle for Fiscal Memory" },
      { 0x6408, "Not enough space for next VAT rate record" },
      { 0x6409, "Fiscal Memory not connected or not formatted" },
      { 0x640A, "The record structure in fiscal memory is not correct" },
      { 0x640B, "Incorrect attempt to read a record from the buffer in RAM" },
      { 0x640C, "No space for temporary data to write" },
      { 0x640D, "Invalid country code or printer model saved in fiscal memory" },
      { 0x640E, "The number of saved headers has reached its maximum" },
      { 0x640F, "Fatal error of Fiscal Memory" },
      { 0x6410, "Fiscal Memory is not compatible with data in RAM. Delete RAM" },
      { 0x6411, "Important records in fiscal memory are damaged" },
      { 0x6412, "Error playing totalizers from fiscal memory." },
      { 0x6413, "Not found" },
      { 0x6414, "Type is not supported" },
      { 0x6415, "Fiscal Memory exchanged" },
      { 0x6416, "Not enough space for next exchange public key record" },
      { 0x7001, "EJ must be ON all the time" },
      { 0x7002, "EJ can not be OFF" },
      { 0x7003, "Can not open the day, all EJ blocks are used, please save EJ data to optical media" },
      { 0x7004, "Can not open the day, not enough space in the EJ flash memory, please save EJ data to optical media" },
      { 0x7005, "The day can not be closed, all EJ blocks are in use, please save EJ data to optical media" },
      { 0x7006, "EJ server is not ready" },
      { 0x7007, "EJ block is not closed or dumped" },
      { 0x7008, "Wrong number of EJ block" },
      { 0x7009, "EJ block is not closed" },
      { 0x700A, "EJ - not enough memory space" },
      { 0x700B, "EJ – damaged data" },
      { 0x700C, "Save to EJ memory is not allowed" },
      { 0x700D, "EJ: no memory space" },
      { 0x700E, "First, the MD5 value must be verified" },
      { 0x700F, "Invalid SHA value for EJ data, please dump the data again" },
      { 0x7010, "The SD card is not signed" },
      { 0x7201, "Format error" },
      { 0x7202, "Data error" },
      { 0x7203, "Another cash model" },
      { 0x7204, "Damaged data" },
      { 0x7205, "No SD card" },
      { 0x7206, "Write verification error" },
      { 0x7207, "No free space on the SD card" },
      { 0x7208, "SD card from another cashier" },
      { 0x7209, "The SD card is closed" },
      { 0x720A, "The SD card is formatted and contains EJ files" },
      { 0x720B, "Error while formatting EJ - SD card" },
      { 0x720C, "Error while create SD card structure" },
      { 0x720D, "SD card can not be closed" },
      { 0x720E, "Unknown print type" },
      { 0x720F, "Requested receipts not found" },
      { 0x7210, "Requested daily report not found" },
      { 0x7211, "Requested fiscal day not found" },
      { 0x7212, "Selected printout could not be printed" },
      { 0x7213, "Can not open file" },
      { 0x7214, "Unable to close the file" },
      { 0x7215, "Out of receipt number" },
      { 0x7216, "Error in file name" },
      { 0x7217, "Error while dump history" },
      { 0x7218, "Error while dump EJ block. The block is not open" },
      { 0x7219, "Error while verifying SD card" },
      { 0x721A, "SD card verification is not possible" },
      { 0x721B, "Internal uninitialized server" },
      { 0x721C, "Internal SD card busy: record data" },
      { 0x721D, "Internal SD card busy: verification of data" },
      { 0x721E, "Internal SD card busy: printing data" },
      { 0x7221, "Stack. Incorrect type size" },
      { 0x7222, "Unallocated memory for the stack" },
      { 0x7223, "The stack is empty" },
      { 0x7224, "Stack overflowed" },
      { 0x7225, "Empty file name" },
      { 0x7226, "The file is not open" },
      { 0x7227, "No memory allocated for file buffer" },
      { 0x7228, "Cannot undo character" },
      { 0x7229, "No data to write to file" },
      { 0x722A, "End of file" },
      { 0x722B, "Operation not allowed" },
      { 0x722C, "Unrecognized part of XML" },
      { 0x722D, "Unauthorized sign" },
      { 0x722E, "Invalid closing element name" },
      { 0x722F, "Incompatible number of openings and closings the elements" },
      { 0x7230, "Found element" },
      { 0x7231, "Element not found" },
      { 0x7232, "The file ends correctly" },
      { 0x7240, "Directory readout was not initiated" },
      { 0x7241, "Data dump was not initiated" },
      { 0x7250, "The requested printout is on another SD card, detailed information on the printout" },
      { 0x7304, "Protected Memory not paired" },
      { 0x7305, "Code page conversion error" },
      { 0x7307, "Protected Memory internal error" },
      { 0x7601, "I / O error" },
      { 0x7602, "Invalid xml data" },
      { 0x7603, "Invalid xml format" },
      { 0x7604, "Exceeded restrictions on xml processing" },
      { 0x7605, "Incorrect operation on xml data" },
      { 0x7701, "Error opening file" },
      { 0x7702, "Error closing file" },
      { 0x7703, "Error reading from file" },
      { 0x7704, "Error writing to file" },
      { 0x7705, "Error while moving file position" },
      { 0x7706, "Error cutting file size" },
      { 0x7707, "Error while selected file open mode" },
      { 0x7708, "Wrong file system" },
      { 0x7709, "Error while synchronizing file" },
      { 0x770A, "Error while creating directory" },
      { 0x770B, "Error while creating file" },
      { 0x770C, "Error while deleted" },
      { 0x8000, "RAM damaged" },
      { 0x8001, "RTC damaged" },
      { 0x8002, "RAM deleted" },
      { 0x8003, "RTC not set" },
      { 0x8004, "Client display is not connected" },
      { 0x8006, "The display driver is already open" },
      { 0x8007, "Low power supply, printing and saving data to Fiscal Memory is not possible" },
      { 0x8008, "Service jumper activated" },
      { 0x8009, "The printer is disconnected" },
      { 0x800A, "Battery voltage for RAM and RTC is too low" },
      { 0x800B, "Fiscal Module problems was detected" },
      { 0x800C, "Flash Programming Jumper Error" },
      { 0x800D, "Boot Source Error" },
      { 0x800E, "No FLASH or FLASH memory is too small" },
      { 0x8010, "Jumper Clear All activated" },
      { 0x8011, "Clear RAM jumper activated" },
      { 0x8012, "The printer is in autonomous mode, please exit the autonomous menu" },
      { 0x8100, "Unsupported printing station" },
      { 0x8101, "No paper (receipt station)" },
      { 0x8102, "No paper (copy station)" },
      { 0x8105, "Printer cover open" },
      { 0x8106, "Paper jam" },
      { 0x8107, "Printhead overheating" },
      { 0x8108, "Cutter error" },
      { 0x8109, "No answer to status question" },
      { 0x810A, "Raised printhead" },
      { 0x810B, "Printer mechanism fatal error" },
      { 0x810C, "Printer locked - service intervention is necessary" },
      { 0x8200, "Invalid display mode" },
      { 0x8201, "No access to the display, fiscal restrictions" },
      { 0x8300, "Graphics not supported" },
      { 0x8301, "Undefined graphics" },
      { 0x8302, "Graphics is already defined" },
      { 0x8303, "The graphics loading session has not been opened" },
      { 0x8304, "The graphics loading session is already open" },
      { 0x8305, "Image number out of acceptable range" },
      { 0x8306, "Image size out of acceptable range" },
      { 0x8307, "Horizontal dimension graphic out of acceptable range" },
      { 0x8308, "Vertical dimension graphic out of acceptable range" },
      { 0x8309, "Too long graphic name" },
      { 0x830A, "Too much data" },
      { 0x830B, "Not enough data" },
      { 0x830C, "Not enough memory" },
      { 0x830D, "Colorful graphics" },
      { 0x830E, "Graphics is set to print" },
      { 0x8500, "TPM is not ready" },
      { 0x8501, "TPM module error" },
      { 0x9000, "Button test failed" },
      { 0x9001, "Clock test failed" },
      { 0x9002, "Drawer test failed" },
      { 0x9003, "LED test failed" },
      { 0x9004, "Port test failed" },
      { 0x9005, "Power failure test" },
      { 0x9006, "Printer test failed" },
      { 0x9007, "Sensor test failed" },
      { 0x9008, "Hardware test failed" },
      { 0x9009, "Internal test failed" },
      { 0x900A, "Heating test failed" },
      { 0x900B, "Flash test failed" },
      { 0x9080, "Test is not implemented" },
      { 0xA000, "Incorrect transmission speed" },
      { 0xA001, "Incorrect protocol ID" },
      { 0xA002, "Incorrect code page ID" },
      { 0xA003, "CFG: not allowed in fiscal mode" },
      { 0xB002, "Too big correction" },
      { 0xB003, "One correct time is required to determine the correction" },
      { 0xB004, "Correction detected the correct operation of the RTC" },
      { 0xB005, "Not enough time has passed for the correction to be made" },
      { 0xB011, "Current time is winter time" },
      { 0xB012, "Current time is summer time" },
      { 0xB013, "Time change not allowed" },
      { 0xB014, "Time change allowed" },
      { 0xD002, "Number out of range" },
      { 0xD003, "Too much loaded data" },
      { 0xD004, "Loading data is not run" },
      { 0xD005, "Too little loaded data" },
      { 0xD006, "Wrong format of loaded certificate/key" },
      { 0xD007, "No communication/TMP error" },
      { 0xD008, "No TPM recording keys" },
      { 0xD009, "Loading error/recording keys to TPM" },
      { 0xD00A, "TLS keys not loaded" },
      { 0xE000, "No answer from CPD Server" },
      { 0xE001, "Denied from CPD Server" },
      { 0xE002, "No certificates" },
      { 0xE003, "CPD Server – serviceman number error" },
      { 0xE004, "CPD Server – NIP number error" },
      { 0xE005, "CPD Service – serial number error" },
      { 0xE007, "Fiscalization refused" },
      { 0xE010, "Data transmission error to Central Repository of Cash register" },
      { 0xE011, "Wrong serial number" },
      { 0xE012, "Wrong unique number" },
      { 0xE013, "Wrong ID number" },
      { 0xE014, "Wrong NIP" },
      { 0xE018, "CPD Server - fiscalization refused, operation not allowed" },
      { 0xE02C, "CPD Server – confirmation of fiscalization – fiscalization not initiated" }
    };

  }
}
