namespace Vera.Poland.Models.Requests
{
  public class SetCashierRequest : PrinterRequest
  {
    /// <summary>
    /// Can be a cashier firstname/lastname combo or any cashier identifier generated by EVA
    /// </summary>
    public string CashierIdentifier { get; set; }
    public string TerminalNumber { get; set; }
  }
}