using System.Collections.Generic;

namespace Vera.Models
{
    public static class Currencies
    {
        public class CurrencyEntry
        {
            public string Name { get; set; }
            public string Code { get; set; }
            public string Number { get; set; }
            public int Precision { get; set; }
        }

        public static Dictionary<string, CurrencyEntry> CodeToCurrencyMapper = new Dictionary<string, CurrencyEntry>
        {
            { "AFN",
             new CurrencyEntry { Code = "AFN", Precision = 2, Number = "971", Name = "Afghani" } },
            { "EUR",
             new CurrencyEntry { Code = "EUR", Precision = 2, Number = "978", Name = "Euro" } },
            { "ALL",
             new CurrencyEntry { Code = "ALL", Precision = 2, Number = "008", Name = "Lek" } },
            { "DZD",
             new CurrencyEntry { Code = "DZD", Precision = 2, Number = "012", Name = "Algerian Dinar" } },
            { "USD",
             new CurrencyEntry { Code = "USD", Precision = 2, Number = "840", Name = "US Dollar" } },
            { "AOA",
             new CurrencyEntry { Code = "AOA", Precision = 2, Number = "973", Name = "Kwanza" } },
            { "XCD",
             new CurrencyEntry { Code = "XCD", Precision = 2, Number = "951", Name = "East Caribbean Dollar" } },
            { "ARS",
             new CurrencyEntry { Code = "ARS", Precision = 2, Number = "032", Name = "Argentine Peso" } },
            { "AMD",
             new CurrencyEntry { Code = "AMD", Precision = 2, Number = "051", Name = "Armenian Dram" } },
            { "AWG",
             new CurrencyEntry { Code = "AWG", Precision = 2, Number = "533", Name = "Aruban Florin" } },
            { "AUD",
             new CurrencyEntry { Code = "AUD", Precision = 2, Number = "036", Name = "Australian Dollar" } },
            { "AZN",
             new CurrencyEntry { Code = "AZN", Precision = 2, Number = "944", Name = "Azerbaijan Manat" } },
            { "BSD",
             new CurrencyEntry { Code = "BSD", Precision = 2, Number = "044", Name = "Bahamian Dollar" } },
            { "BHD",
             new CurrencyEntry { Code = "BHD", Precision = 3, Number = "048", Name = "Bahraini Dinar" } },
            { "BDT",
             new CurrencyEntry { Code = "BDT", Precision = 2, Number = "050", Name = "Taka" } },
            { "BBD",
             new CurrencyEntry { Code = "BBD", Precision = 2, Number = "052", Name = "Barbados Dollar" } },
            { "BYN",
             new CurrencyEntry { Code = "BYN", Precision = 2, Number = "933", Name = "Belarusian Ruble" } },
            { "BZD",
             new CurrencyEntry { Code = "BZD", Precision = 2, Number = "084", Name = "Belize Dollar" } },
            { "XOF",
             new CurrencyEntry { Code = "XOF", Precision = 0, Number = "952", Name = "CFA Franc BCEAO" } },
            { "BMD",
             new CurrencyEntry { Code = "BMD", Precision = 2, Number = "060", Name = "Bermudian Dollar" } },
            { "INR",
             new CurrencyEntry { Code = "INR", Precision = 2, Number = "356", Name = "Indian Rupee" } },
            { "BTN",
             new CurrencyEntry { Code = "BTN", Precision = 2, Number = "064", Name = "Ngultrum" } },
            { "BOB",
             new CurrencyEntry { Code = "BOB", Precision = 2, Number = "068", Name = "Boliviano" } },
            { "BOV",
             new CurrencyEntry { Code = "BOV", Precision = 2, Number = "984", Name = "Mvdol" } },
            { "BAM",
             new CurrencyEntry { Code = "BAM", Precision = 2, Number = "977", Name = "Convertible Mark" } },
            { "BWP",
             new CurrencyEntry { Code = "BWP", Precision = 2, Number = "072", Name = "Pula" } },
            { "NOK",
             new CurrencyEntry { Code = "NOK", Precision = 2, Number = "578", Name = "Norwegian Krone" } },
            { "BRL",
             new CurrencyEntry { Code = "BRL", Precision = 2, Number = "986", Name = "Brazilian Real" } },
            { "BND",
             new CurrencyEntry { Code = "BND", Precision = 2, Number = "096", Name = "Brunei Dollar" } },
            { "BGN",
             new CurrencyEntry { Code = "BGN", Precision = 2, Number = "975", Name = "Bulgarian Lev" } },
            { "BIF",
             new CurrencyEntry { Code = "BIF", Precision = 0, Number = "108", Name = "Burundi Franc" } },
            { "CVE",
             new CurrencyEntry { Code = "CVE", Precision = 2, Number = "132", Name = "Cabo Verde Escudo" } },
            { "KHR",
             new CurrencyEntry { Code = "KHR", Precision = 2, Number = "116", Name = "Riel" } },
            { "XAF",
             new CurrencyEntry { Code = "XAF", Precision = 0, Number = "950", Name = "CFA Franc BEAC" } },
            { "CAD",
             new CurrencyEntry { Code = "CAD", Precision = 2, Number = "124", Name = "Canadian Dollar" } },
            { "KYD",
             new CurrencyEntry { Code = "KYD", Precision = 2, Number = "136", Name = "Cayman Islands Dollar" } },
            { "CLP",
             new CurrencyEntry { Code = "CLP", Precision = 0, Number = "152", Name = "Chilean Peso" } },
            { "CLF",
             new CurrencyEntry { Code = "CLF", Precision = 4, Number = "990", Name = "Unidad de Fomento" } },
            { "CNY",
             new CurrencyEntry { Code = "CNY", Precision = 2, Number = "156", Name = "Yuan Renminbi" } },
            { "COP",
             new CurrencyEntry { Code = "COP", Precision = 2, Number = "170", Name = "Colombian Peso" } },
            { "COU",
             new CurrencyEntry { Code = "COU", Precision = 2, Number = "970", Name = "Unidad de Valor Real" } },
            { "KMF",
             new CurrencyEntry { Code = "KMF", Precision = 0, Number = "174", Name = "Comorian Franc " } },
            { "CDF",
             new CurrencyEntry { Code = "CDF", Precision = 2, Number = "976", Name = "Congolese Franc" } },
            { "NZD",
             new CurrencyEntry { Code = "NZD", Precision = 2, Number = "554", Name = "New Zealand Dollar" } },
            { "CRC",
             new CurrencyEntry { Code = "CRC", Precision = 2, Number = "188", Name = "Costa Rican Colon" } },
            { "HRK",
             new CurrencyEntry { Code = "HRK", Precision = 2, Number = "191", Name = "Kuna" } },
            { "CUP",
             new CurrencyEntry { Code = "CUP", Precision = 2, Number = "192", Name = "Cuban Peso" } },
            { "CUC",
             new CurrencyEntry { Code = "CUC", Precision = 2, Number = "931", Name = "Peso Convertible" } },
            { "ANG",
             new CurrencyEntry { Code = "ANG", Precision = 2, Number = "532", Name = "Netherlands Antillean Guilder" } },
            { "CZK",
             new CurrencyEntry { Code = "CZK", Precision = 2, Number = "203", Name = "Czech Koruna" } },
            { "DKK",
             new CurrencyEntry { Code = "DKK", Precision = 2, Number = "208", Name = "Danish Krone" } },
            { "DJF",
             new CurrencyEntry { Code = "DJF", Precision = 0, Number = "262", Name = "Djibouti Franc" } },
            { "DOP",
             new CurrencyEntry { Code = "DOP", Precision = 2, Number = "214", Name = "Dominican Peso" } },
            { "EGP",
             new CurrencyEntry { Code = "EGP", Precision = 2, Number = "818", Name = "Egyptian Pound" } },
            { "SVC",
             new CurrencyEntry { Code = "SVC", Precision = 2, Number = "222", Name = "El Salvador Colon" } },
            { "ERN",
             new CurrencyEntry { Code = "ERN", Precision = 2, Number = "232", Name = "Nakfa" } },
            { "SZL",
             new CurrencyEntry { Code = "SZL", Precision = 2, Number = "748", Name = "Lilangeni" } },
            { "ETB",
             new CurrencyEntry { Code = "ETB", Precision = 2, Number = "230", Name = "Ethiopian Birr" } },
            { "FKP",
             new CurrencyEntry { Code = "FKP", Precision = 2, Number = "238", Name = "Falkland Islands Pound" } },
            { "FJD",
             new CurrencyEntry { Code = "FJD", Precision = 2, Number = "242", Name = "Fiji Dollar" } },
            { "XPF",
             new CurrencyEntry { Code = "XPF", Precision = 0, Number = "953", Name = "CFP Franc" } },
            { "GMD",
             new CurrencyEntry { Code = "GMD", Precision = 2, Number = "270", Name = "Dalasi" } },
            { "GEL",
             new CurrencyEntry { Code = "GEL", Precision = 2, Number = "981", Name = "Lari" } },
            { "GHS",
             new CurrencyEntry { Code = "GHS", Precision = 2, Number = "936", Name = "Ghana Cedi" } },
            { "GIP",
             new CurrencyEntry { Code = "GIP", Precision = 2, Number = "292", Name = "Gibraltar Pound" } },
            { "GTQ",
             new CurrencyEntry { Code = "GTQ", Precision = 2, Number = "320", Name = "Quetzal" } },
            { "GBP",
             new CurrencyEntry { Code = "GBP", Precision = 2, Number = "826", Name = "Pound Sterling" } },
            { "GNF",
             new CurrencyEntry { Code = "GNF", Precision = 0, Number = "324", Name = "Guinean Franc" } },
            { "GYD",
             new CurrencyEntry { Code = "GYD", Precision = 2, Number = "328", Name = "Guyana Dollar" } },
            { "HTG",
             new CurrencyEntry { Code = "HTG", Precision = 2, Number = "332", Name = "Gourde" } },
            { "HNL",
             new CurrencyEntry { Code = "HNL", Precision = 2, Number = "340", Name = "Lempira" } },
            { "HKD",
             new CurrencyEntry { Code = "HKD", Precision = 2, Number = "344", Name = "Hong Kong Dollar" } },
            { "HUF",
             new CurrencyEntry { Code = "HUF", Precision = 2, Number = "348", Name = "Forint" } },
            { "ISK",
             new CurrencyEntry { Code = "ISK", Precision = 0, Number = "352", Name = "Iceland Krona" } },
            { "IDR",
             new CurrencyEntry { Code = "IDR", Precision = 2, Number = "360", Name = "Rupiah" } },
            { "XDR",
             new CurrencyEntry { Code = "XDR", Precision = 0, Number = "960", Name = "SDR (Special Drawing Right)" } },
            { "IRR",
             new CurrencyEntry { Code = "IRR", Precision = 2, Number = "364", Name = "Iranian Rial" } },
            { "IQD",
             new CurrencyEntry { Code = "IQD", Precision = 3, Number = "368", Name = "Iraqi Dinar" } },
            { "ILS",
             new CurrencyEntry { Code = "ILS", Precision = 2, Number = "376", Name = "New Israeli Sheqel" } },
            { "JMD",
             new CurrencyEntry { Code = "JMD", Precision = 2, Number = "388", Name = "Jamaican Dollar" } },
            { "JPY",
             new CurrencyEntry { Code = "JPY", Precision = 0, Number = "392", Name = "Yen" } },
            { "JOD",
             new CurrencyEntry { Code = "JOD", Precision = 3, Number = "400", Name = "Jordanian Dinar" } },
            { "KZT",
             new CurrencyEntry { Code = "KZT", Precision = 2, Number = "398", Name = "Tenge" } },
            { "KES",
             new CurrencyEntry { Code = "KES", Precision = 2, Number = "404", Name = "Kenyan Shilling" } },
            { "KPW",
             new CurrencyEntry { Code = "KPW", Precision = 2, Number = "408", Name = "North Korean Won" } },
            { "KRW",
             new CurrencyEntry { Code = "KRW", Precision = 0, Number = "410", Name = "Won" } },
            { "KWD",
             new CurrencyEntry { Code = "KWD", Precision = 3, Number = "414", Name = "Kuwaiti Dinar" } },
            { "KGS",
             new CurrencyEntry { Code = "KGS", Precision = 2, Number = "417", Name = "Som" } },
            { "LAK",
             new CurrencyEntry { Code = "LAK", Precision = 2, Number = "418", Name = "Lao Kip" } },
            { "LBP",
             new CurrencyEntry { Code = "LBP", Precision = 2, Number = "422", Name = "Lebanese Pound" } },
            { "LSL",
             new CurrencyEntry { Code = "LSL", Precision = 2, Number = "426", Name = "Loti" } },
            { "ZAR",
             new CurrencyEntry { Code = "ZAR", Precision = 2, Number = "710", Name = "Rand" } },
            { "LRD",
             new CurrencyEntry { Code = "LRD", Precision = 2, Number = "430", Name = "Liberian Dollar" } },
            { "LYD",
             new CurrencyEntry { Code = "LYD", Precision = 3, Number = "434", Name = "Libyan Dinar" } },
            { "CHF",
             new CurrencyEntry { Code = "CHF", Precision = 2, Number = "756", Name = "Swiss Franc" } },
            { "MOP",
             new CurrencyEntry { Code = "MOP", Precision = 2, Number = "446", Name = "Pataca" } },
            { "MKD",
             new CurrencyEntry { Code = "MKD", Precision = 2, Number = "807", Name = "Denar" } },
            { "MGA",
             new CurrencyEntry { Code = "MGA", Precision = 2, Number = "969", Name = "Malagasy Ariary" } },
            { "MWK",
             new CurrencyEntry { Code = "MWK", Precision = 2, Number = "454", Name = "Malawi Kwacha" } },
            { "MYR",
             new CurrencyEntry { Code = "MYR", Precision = 2, Number = "458", Name = "Malaysian Ringgit" } },
            { "MVR",
             new CurrencyEntry { Code = "MVR", Precision = 2, Number = "462", Name = "Rufiyaa" } },
            { "MRU",
             new CurrencyEntry { Code = "MRU", Precision = 2, Number = "929", Name = "Ouguiya" } },
            { "MUR",
             new CurrencyEntry { Code = "MUR", Precision = 2, Number = "480", Name = "Mauritius Rupee" } },
            { "XUA",
             new CurrencyEntry { Code = "XUA", Precision = 0, Number = "965", Name = "ADB Unit of Account" } },
            { "MXN",
             new CurrencyEntry { Code = "MXN", Precision = 2, Number = "484", Name = "Mexican Peso" } },
            { "MXV",
             new CurrencyEntry { Code = "MXV", Precision = 2, Number = "979", Name = "Mexican Unidad de Inversion (UDI)" } },
            { "MDL",
             new CurrencyEntry { Code = "MDL", Precision = 2, Number = "498", Name = "Moldovan Leu" } },
            { "MNT",
             new CurrencyEntry { Code = "MNT", Precision = 2, Number = "496", Name = "Tugrik" } },
            { "MAD",
             new CurrencyEntry { Code = "MAD", Precision = 2, Number = "504", Name = "Moroccan Dirham" } },
            { "MZN",
             new CurrencyEntry { Code = "MZN", Precision = 2, Number = "943", Name = "Mozambique Metical" } },
            { "MMK",
             new CurrencyEntry { Code = "MMK", Precision = 2, Number = "104", Name = "Kyat" } },
            { "NAD",
             new CurrencyEntry { Code = "NAD", Precision = 2, Number = "516", Name = "Namibia Dollar" } },
            { "NPR",
             new CurrencyEntry { Code = "NPR", Precision = 2, Number = "524", Name = "Nepalese Rupee" } },
            { "NIO",
             new CurrencyEntry { Code = "NIO", Precision = 2, Number = "558", Name = "Cordoba Oro" } },
            { "NGN",
             new CurrencyEntry { Code = "NGN", Precision = 2, Number = "566", Name = "Naira" } },
            { "OMR",
             new CurrencyEntry { Code = "OMR", Precision = 3, Number = "512", Name = "Rial Omani" } },
            { "PKR",
             new CurrencyEntry { Code = "PKR", Precision = 2, Number = "586", Name = "Pakistan Rupee" } },
            { "PAB",
             new CurrencyEntry { Code = "PAB", Precision = 2, Number = "590", Name = "Balboa" } },
            { "PGK",
             new CurrencyEntry { Code = "PGK", Precision = 2, Number = "598", Name = "Kina" } },
            { "PYG",
             new CurrencyEntry { Code = "PYG", Precision = 0, Number = "600", Name = "Guarani" } },
            { "PEN",
             new CurrencyEntry { Code = "PEN", Precision = 2, Number = "604", Name = "Sol" } },
            { "PHP",
             new CurrencyEntry { Code = "PHP", Precision = 2, Number = "608", Name = "Philippine Peso" } },
            { "PLN",
             new CurrencyEntry { Code = "PLN", Precision = 2, Number = "985", Name = "Zloty" } },
            { "QAR",
             new CurrencyEntry { Code = "QAR", Precision = 2, Number = "634", Name = "Qatari Rial" } },
            { "RON",
             new CurrencyEntry { Code = "RON", Precision = 2, Number = "946", Name = "Romanian Leu" } },
            { "RUB",
             new CurrencyEntry { Code = "RUB", Precision = 2, Number = "643", Name = "Russian Ruble" } },
            { "RWF",
             new CurrencyEntry { Code = "RWF", Precision = 0, Number = "646", Name = "Rwanda Franc" } },
            { "SHP",
             new CurrencyEntry { Code = "SHP", Precision = 2, Number = "654", Name = "Saint Helena Pound" } },
            { "WST",
             new CurrencyEntry { Code = "WST", Precision = 2, Number = "882", Name = "Tala" } },
            { "STN",
             new CurrencyEntry { Code = "STN", Precision = 2, Number = "930", Name = "Dobra" } },
            { "SAR",
             new CurrencyEntry { Code = "SAR", Precision = 2, Number = "682", Name = "Saudi Riyal" } },
            { "RSD",
             new CurrencyEntry { Code = "RSD", Precision = 2, Number = "941", Name = "Serbian Dinar" } },
            { "SCR",
             new CurrencyEntry { Code = "SCR", Precision = 2, Number = "690", Name = "Seychelles Rupee" } },
            { "SLL",
             new CurrencyEntry { Code = "SLL", Precision = 2, Number = "694", Name = "Leone" } },
            { "SGD",
             new CurrencyEntry { Code = "SGD", Precision = 2, Number = "702", Name = "Singapore Dollar" } },
            { "XSU",
             new CurrencyEntry { Code = "XSU", Precision = 0, Number = "994", Name = "Sucre" } },
            { "SBD",
             new CurrencyEntry { Code = "SBD", Precision = 2, Number = "090", Name = "Solomon Islands Dollar" } },
            { "SOS",
             new CurrencyEntry { Code = "SOS", Precision = 2, Number = "706", Name = "Somali Shilling" } },
            { "SSP",
             new CurrencyEntry { Code = "SSP", Precision = 2, Number = "728", Name = "South Sudanese Pound" } },
            { "LKR",
             new CurrencyEntry { Code = "LKR", Precision = 2, Number = "144", Name = "Sri Lanka Rupee" } },
            { "SDG",
             new CurrencyEntry { Code = "SDG", Precision = 2, Number = "938", Name = "Sudanese Pound" } },
            { "SRD",
             new CurrencyEntry { Code = "SRD", Precision = 2, Number = "968", Name = "Surinam Dollar" } },
            { "SEK",
             new CurrencyEntry { Code = "SEK", Precision = 2, Number = "752", Name = "Swedish Krona" } },
            { "CHE",
             new CurrencyEntry { Code = "CHE", Precision = 2, Number = "947", Name = "WIR Euro" } },
            { "CHW",
             new CurrencyEntry { Code = "CHW", Precision = 2, Number = "948", Name = "WIR Franc" } },
            { "SYP",
             new CurrencyEntry { Code = "SYP", Precision = 2, Number = "760", Name = "Syrian Pound" } },
            { "TWD",
             new CurrencyEntry { Code = "TWD", Precision = 2, Number = "901", Name = "New Taiwan Dollar" } },
            { "TJS",
             new CurrencyEntry { Code = "TJS", Precision = 2, Number = "972", Name = "Somoni" } },
            { "TZS",
             new CurrencyEntry { Code = "TZS", Precision = 2, Number = "834", Name = "Tanzanian Shilling" } },
            { "THB",
             new CurrencyEntry { Code = "THB", Precision = 2, Number = "764", Name = "Baht" } },
            { "TOP",
             new CurrencyEntry { Code = "TOP", Precision = 2, Number = "776", Name = "Pa'anga" } },
            { "TTD",
             new CurrencyEntry { Code = "TTD", Precision = 2, Number = "780", Name = "Trinidad and Tobago Dollar" } },
            { "TND",
             new CurrencyEntry { Code = "TND", Precision = 3, Number = "788", Name = "Tunisian Dinar" } },
            { "TRY",
             new CurrencyEntry { Code = "TRY", Precision = 2, Number = "949", Name = "Turkish Lira" } },
            { "TMT",
             new CurrencyEntry { Code = "TMT", Precision = 2, Number = "934", Name = "Turkmenistan New Manat" } },
            { "UGX",
             new CurrencyEntry { Code = "UGX", Precision = 0, Number = "800", Name = "Uganda Shilling" } },
            { "UAH",
             new CurrencyEntry { Code = "UAH", Precision = 2, Number = "980", Name = "Hryvnia" } },
            { "AED",
             new CurrencyEntry { Code = "AED", Precision = 2, Number = "784", Name = "UAE Dirham" } },
            { "USN",
             new CurrencyEntry { Code = "USN", Precision = 2, Number = "997", Name = "US Dollar (Next day)" } },
            { "UYU",
             new CurrencyEntry { Code = "UYU", Precision = 2, Number = "858", Name = "Peso Uruguayo" } },
            { "UYI",
             new CurrencyEntry { Code = "UYI", Precision = 0, Number = "940", Name = "Uruguay Peso en Unidades Indexadas (UI)" } },
            { "UYW",
             new CurrencyEntry { Code = "UYW", Precision = 4, Number = "927", Name = "Unidad Previsional" } },
            { "UZS",
             new CurrencyEntry { Code = "UZS", Precision = 2, Number = "860", Name = "Uzbekistan Sum" } },
            { "VUV",
             new CurrencyEntry { Code = "VUV", Precision = 0, Number = "548", Name = "Vatu" } },
            { "VES",
             new CurrencyEntry { Code = "VES", Precision = 2, Number = "928", Name = "Bolívar Soberano" } },
            { "VND",
             new CurrencyEntry { Code = "VND", Precision = 0, Number = "704", Name = "Dong" } },
            { "YER",
             new CurrencyEntry { Code = "YER", Precision = 2, Number = "886", Name = "Yemeni Rial" } },
            { "ZMW",
             new CurrencyEntry { Code = "ZMW", Precision = 2, Number = "967", Name = "Zambian Kwacha" } },
            { "ZWL",
             new CurrencyEntry { Code = "ZWL", Precision = 2, Number = "932", Name = "Zimbabwe Dollar" } },
            { "XBA",
             new CurrencyEntry { Code = "XBA", Precision = 0, Number = "955", Name = "Bond Markets Unit European Composite Unit (EURCO)" } },
            { "XBB",
             new CurrencyEntry { Code = "XBB", Precision = 0, Number = "956", Name = "Bond Markets Unit European Monetary Unit (E.M.U.-6)" } },
            { "XBC",
             new CurrencyEntry { Code = "XBC", Precision = 0, Number = "957", Name = "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)" } },
            { "XBD",
             new CurrencyEntry { Code = "XBD", Precision = 0, Number = "958", Name = "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)" } },
            { "XTS",
             new CurrencyEntry { Code = "XTS", Precision = 0, Number = "963", Name = "Codes specifically reserved for testing purposes" } },
            { "XXX",
             new CurrencyEntry { Code = "XXX", Precision = 0, Number = "999", Name = "The codes assigned for transactions where no currency is involved" } },
            { "XAU",
             new CurrencyEntry { Code = "XAU", Precision = 0, Number = "959", Name = "Gold" } },
            { "XPD",
             new CurrencyEntry { Code = "XPD", Precision = 0, Number = "964", Name = "Palladium" } },
            { "XPT",
             new CurrencyEntry { Code = "XPT", Precision = 0, Number = "962", Name = "Platinum" } },
            { "XAG",
             new CurrencyEntry { Code = "XAG", Precision = 0, Number = "961", Name = "Silver" } },
        };
    }
}
