name: Publish Vera Nuget packages
on:
  push:
    branches:
      - master
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.102'
        source-url: https://nuget.pkg.github.com/new-black/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Package Vera.Documents
      run: dotnet pack --configuration Release src/Vera.Documents
    - name: Publish Vera.Documents
      run: dotnet nuget push src/Vera.Documents/out/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/new-black/index.json --skip-duplicate --no-symbols true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package Vera.Grpc
      run: dotnet pack --configuration Release src/Vera.Grpc
    - name: Publish Vera.Grpc
      run: dotnet nuget push src/Vera.Grpc/out/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/new-black/index.json --skip-duplicate --no-symbols true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
