name: NuGet Vera.Documents
on:
  push:
    branches:
      - master

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.102'
        source-url: https://nuget.pkg.github.com/new-black/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Package
      run: dotnet pack --configuration Release src/Vera.Documents
    - name: Publish the package to GPR
      run: dotnet nuget push src/Vera.Documents/bin/Release/*.nupkg --skip-duplicate